### ISSUE TITLE
Additional Keymappings

### ISSUE THREAD

**Issue by EHLOVader** [ShawnMcCool/PHPStorm-SpacePeacock#8]
There are still quite a few keymaps I have had to add. 

I would like to [upload a PR](https://gist.github.com/EHLOVader/962e25704d25f3eeceb4) but am unsure how to do it. Do you use the [settings repository](https://github.com/develar/settings-repository)? It produces an XML file for the keymaps. I am unsure how you handle the export of your settings now, but if you use that for data here, and then use github release to distribute the binaries you have in here. https://github.com/blog/1547-release-your-software

**Comment by EHLOVader** [comment]
Here are the highlights of the keymap:
  * <kbd>F4</kbd> Maps to `DomCollectionControl.Edit`
  * <kbd>F4</kbd> Maps to `DomElementsTreeView.GotoDomElementDeclarationAction`
  * <kbd>F4</kbd> Maps to `EditSource`
  * <kbd>meta</kbd> + <kbd>DOWN</kbd> Maps to `EditorTextEnd`
  * <kbd>shift</kbd> + <kbd>meta</kbd> + <kbd>DOWN</kbd> Maps to `EditorTextEndWithSelection`
  * <kbd>meta</kbd> + <kbd>UP</kbd> Maps to `EditorTextStart`
  * <kbd>shift</kbd> + <kbd>meta</kbd> + <kbd>UP</kbd> Maps to `EditorTextStartWithSelection`
  * <kbd>control</kbd> + <kbd>meta</kbd> + <kbd>DOWN</kbd> Maps to `MoveLineDown`
  * <kbd>control</kbd> + <kbd>meta</kbd> + <kbd>UP</kbd> Maps to `MoveLineUp`
  * <kbd>shift</kbd> + <kbd>control</kbd> + <kbd>meta</kbd> + <kbd>DOWN</kbd> Maps to `MoveStatementDown`
  * <kbd>shift</kbd> + <kbd>control</kbd> + <kbd>meta</kbd> + <kbd>UP</kbd> Maps to `MoveStatementUp`

**Comment by ShawnMcCool** [comment]
I simply hit EXPORT and choose visual settings and keymap.

Are you running a mac because some of these, like move line up / down seem to be already in there.

Mac and Windows/Linux controls are stored separately, is why I ask.

**Comment by EHLOVader** [comment]
Ah, I thought I loaded the osx keymaps afterwards per instructions.

I knew I could export the binary version but that doesn't look very nice here in Github. 
It wouldn't be clear what had changed I guess.

I will revisit tomorrow and try to import again to confirm. But this one does state that it was based on "Mac OS X 10.5+ Sublime" which I thought was the second settings file I added. 

I forget what but Control+meta+up/down were both on something like jump to source, or lookup references instead of moving when I started tinkering with the keys.

**Comment by EHLOVader** [comment]
Closing for now, I can't reproduce it by importing the settings. I see strange things though, like the other key combos remain. Which doesn't make sense. Review again tomorrow and maybe start from scratch.

**Comment by ShawnMcCool** [comment]
I would be very happy to collaborate with you to improve and unify the Windows / Linux configurations with the OSX configurations. 

I would also like to move these into different repositories as the visual theme, for example.

Maybe a new organization for improving Jetbrains IDE configurations. Providing a number of different visual themes and key configurations. 

Just a thought.

**Comment by EHLOVader** [comment]
Looked at this again. I extracted the jar and took a look at the xml. Those keycombos weren't in there. So I don't know what was happening with my imports. 

[Here is what I got.](https://gist.github.com/EHLOVader/b2ea6f3ced5cb6736cd5) I might fork and commit the extracted files later today. 

Would love to help though.

**Comment by EHLOVader** [comment]
I moved those keymaps into PR #10.
